hepsi: derle calistir
derle:
	g++ -I ./include/ -o ./lib/Sebze.o -c ./src/Sebze.cpp
	g++ -I ./include/ -o ./lib/Meyve.o -c ./src/Meyve.cpp
	g++ -I ./include/ -o ./bin/Test ./lib/Sebze.o ./lib/Meyve.o ./src/Test.cpp
	
calistir:
	./bin/deneme
