hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/Sayi.o -c ./src/Sayi.cpp
	g++ -I ./include/ -o ./lib/Kisi.o -c ./src/Kisi.cpp
	g++ -I ./include/ -o ./bin/Test ./lib/Sayi.o ./lib/Kisi.o ./src/Test.cpp
	
calistir:
	./bin/Test
	
