hepsi: hatalar derle calistir

hatalar:
	g++ -I ./include/ -o ./lib/Exception.o -c ./src/Exception.cpp

derle:	
	g++ -I ./include/ -o ./bin/Test ./lib/Exception.o ./src/Test.cpp

calistir:
	./bin/Test
