hepsi: derle calistir

derle:
	mkdir lib
	mkdir bin
	g++ -I ./include/ -o ./lib/Ogrenci.o -c ./src/Ogrenci.cpp
	g++ -I ./include/ -o ./bin/deneme ./lib/Ogrenci.o ./src/deneme.cpp

calistir:
	./bin/deneme
